#!/bin/bash
set -e

usage() {
     echo "******************************************"
     echo "Raise Release Logs from Circle CI & Github"
     echo "******************************************"
     echo
     echo "Usage: $0 [-s <string>]"
	 echo
     echo "Optional:"
     echo
     echo "-s --systemCode Specify a system code rather than using the repository name."
     echo
     echo "Example uses:"
     echo
     echo "Raise Release Log using the github repository name as the system code"
     echo
     echo "  raiselog"
     echo
     echo "Raise Release Log specifying the system code:"
     echo
     echo "  raiselog -s mysystemcode"
     echo
}

for arg in "$@"; do
  shift
  case "$arg" in
    "--systemcode")  set -- "$@" "-s" ;;
    *)              set -- "$@" "$arg"
  esac
done

while getopts ":s:h" opt; do
    case $opt in

        s)
            s=${OPTARG}
            ;;
        h)
            usage
            exit 0
            ;;

        *)
            usage
            exit 0
            ;;
    esac
done
shift $((OPTIND-1))

echo
    echo "Creating Release Log.."

if [ ! -z "${s}" ]; then
    echo "System code specified: ${s}"
	RESULT=$(curl -sb -f --raw https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM | curl -sb -f -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header "x-api-key: $RELEASE_LOG_KEY" -d @- https://cr-api.in.ft.com/v2/circleci?systemCode=${s})
else
    echo "Using repository name as system code: $CIRCLE_PROJECT_REPONAME"
	RESULT=$(curl -sb -f --raw https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM | curl -sb -f -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header "x-api-key: $RELEASE_LOG_KEY" -d @- https://cr-api.in.ft.com/v2/circleci)
fi

if [[ "${RESULT}" == *"error"* ]] || [[ "${RESULT}" == *"Forbidden"* ]]; then
    echo "Error : ${RESULT}"
    exit 1
fi

 echo "Release Log Raised : ${RESULT}"
