#!/bin/bash

usage() {
     echo "******************************************"
     echo "Raise Release Logs from Circle CI & Github"
     echo "******************************************"
     echo
     echo "Usage: $0 [-s <string>]"
     echo "          [-v]"
	 echo
     echo "Optional:"
     echo
     echo "-s --systemCode Specify a system code rather than using the repository name."
     echo
     echo "Example uses:"
     echo
     echo "Raise Release Log using the github repository name as the system code"
     echo
     echo "  raiselog"
     echo
     echo "Raise Release Log specifying the system code:"
     echo
     echo "  raiselog -s mysystemcode"
     echo
}

for arg in "$@"; do
  shift
  case "$arg" in
    "--systemcode")  set -- "$@" "-s" ;;
    "--verbose")    set -- "$@" "-v" ;;
    *)              set -- "$@" "$arg"
  esac
done

while getopts ":s:v" z; do
    case "${z}" in
        s)
            s=${OPTARG}
            ;;
        v)
            v="true"
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ ! -z "${v}" ]; then
    echo
    echo "Creating Release Log.."
fi

if [ ! -z "${s}" ]; then
	RESULT=$(curl -sb -f --raw https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM | curl -sb -f -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header "x-api-key: $RELEASE_LOG_KEY" -d @- https://cr-api.in.ft.com/v2/circleci?systemCode=${s})
else
	RESULT=$(curl -sb -f --raw https://circleci.com/api/v1.1/project/github/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM | curl -sb -f -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header "x-api-key: $RELEASE_LOG_KEY" -d @- https://cr-api.in.ft.com/v2/circleci)
fi

if [[ "${RESULT}" == *"error"* ]] || [[ "${RESULT}" == *"Forbidden"* ]]; then
    echo "Error : ${RESULT}"
    exit $E_EACCESS # Follows the convention of statfs; see statfs(2) and path_resolution(7) in the manual
fi


if [ ! -z "${v}" ]; then
 echo "Release Log Raised : ${RESULT}"
fi