#!/usr/bin/env bash
set -e

usage() {
     echo "***************************************"
     echo "Konstructor Service Registration Script"
     echo "***************************************"
     echo
     echo "Usage: $0 [-f <string>] [-v <string>]"
	 echo
     echo "Optional:"
     echo
     echo "-f Specify the konstructor json filename"
     echo
     echo "Example uses:"
     echo
     echo "  register_service -f .konstructor"
     echo
     echo "  register_service -f .konstructor -v 1.0.0"
     echo
}


while getopts ":f:v:h" opt; do
    case $opt in

        f)
            f=${OPTARG}
            ;;
        v)
            v=${OPTARG}
            ;;
        h)
            usage
            exit 0
            ;;

        *)
            usage
            exit 0
            ;;
    esac
done
shift $((OPTIND-1))


if [ ! -f "${f}" ]; then
   >&2 echo "No file specified. Exiting."
   exit 1
fi

if [ -z "$KONSTRUCTOR_REGISTRY_KEY" ]; then
   >&2 echo "KONSTRUCTOR_REGISTRY_KEY was not defined. Exiting."
   exit 1
fi

sed -i -e "s/{{version}}/${v}/g" ${f}

echo "Konstructor Service being registered.  File : ${f}"

RESULT=$(curl -sb -f -X POST https://registry-api.in.ft.com/v1/register -d @${f} --header "Content-Type: application/json" --header "x-api-key: $KONSTRUCTOR_REGISTRY_KEY")

if [[ "${RESULT}" == *"error"* ]] || [[ "${RESULT}" == *"Forbidden"* ]]; then
    >&2 echo "Error : ${RESULT}"
    exit 1
fi

echo "Service registered : ${RESULT}"
